//! Icon sets: original SVGs under `assets/icons/<set>/<name>.svg` (generated by
//! `assets/icons/gen_icons.py`; `line` is Lucide). Every set provides every canonical name.

#[cfg(test)]
const MANIFEST: &str = include_str!("../../assets/icons/manifest.json");

type Table = &'static [(&'static str, &'static [u8])];

macro_rules! table {
    ($dir:literal: $($n:literal),* $(,)?) => {
        &[$(($n, include_bytes!(concat!("../../assets/icons/", $dir, "/", $n, ".svg")))),*]
    };
}
macro_rules! all_sets {
    ($($n:literal),* $(,)?) => {
        static LINE: Table = table!("line": $($n),*);
        static AERO: Table = table!("aero": $($n),*);
        static PIXEL: Table = table!("pixel": $($n),*);
    };
}
all_sets!(
    "play",
    "pause",
    "stop",
    "prev",
    "next",
    "shuffle",
    "repeat",
    "repeat-one",
    "volume",
    "volume-low",
    "mute",
    "heart",
    "search",
    "library",
    "now",
    "lists",
    "discover",
    "settings",
    "add",
    "close",
    "back",
    "forward",
    "down",
    "sort-up",
    "sort-down",
    "more",
    "refresh",
    "music",
    "lyrics",
    "history",
    "user",
    "list",
    "check",
    "equalizer",
    "no-image",
    "folder",
    "playlist-add"
);

pub const SETS: [&str; 3] = ["line", "aero", "pixel"];

/// Normalises a config value to a known set name.
pub fn parse(set: &str) -> &'static str {
    SETS.iter().copied().find(|s| *s == set).unwrap_or("line")
}

fn table(set: &str) -> Table {
    match parse(set) {
        "aero" => AERO,
        "pixel" => PIXEL,
        _ => LINE,
    }
}

/// SVG bytes of an icon, `None` for an unknown name.
pub fn svg(set: &str, name: &str) -> Option<&'static [u8]> {
    table(set).iter().find(|(n, _)| *n == name).map(|(_, b)| *b)
}

/// Only the Line set is recoloured with the text colour; Aero and Pixel keep their own colours.
pub fn mono(set: &str) -> bool {
    parse(set) == "line"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_set_provides_every_icon() {
        let man: serde_json::Value = serde_json::from_str(MANIFEST).unwrap();
        let names: Vec<&str> = man["names"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        assert!(names.len() >= 30);
        for set in SETS {
            assert_eq!(table(set).len(), names.len(), "{set}");
            for n in &names {
                let b = svg(set, n).unwrap_or_else(|| panic!("{set}/{n} missing"));
                assert!(
                    b.starts_with(b"<svg") || b.starts_with(b"<?xml"),
                    "{set}/{n}"
                );
            }
        }
    }

    #[test]
    fn unknown_set_falls_back_to_line() {
        assert_eq!(parse("nope"), "line");
        assert!(mono("line") && !mono("pixel") && !mono("aero"));
    }
}
